var findTheDifference = function(s, t) {

1.	//Both provided parameters are strings, we want to be able to access each letter
	  //We do that by converting them into arrays, using the split method.
	  //After splitting, we chain it with the sort function because as we are told, the second argument(t) is generated by random shuffling.
2.  //Because we are comparing 't' with 's', we want to iterate through argument 't' by using a forloop. 
3.  //While we are going through the iteration, we want create a conditional to see if any elements iterated do not match.
4.  //We return the element that does not match any of th elements in the first argument.
  
var findTheDifference = function(s, t) {

  var arrS = s.split("").sort();     //1
  var arrT = t.split("").sort();  
  for(i = 0; i < arrT.length; i++){  //2
    if(arrS[i] !== arrT[i]){         //3
      return arrT[i]                 //4
    }
  }  
};

findTheDifference('abcd', 'abcde')
